Feature: [SysRS-68525] Macro navigator slider

Narrative: The system Timeline view shall have a Macro navigator with a sliding window about the time frame that is displayed in the bottom Timeline section.


Background:
Given the [DEFAULT-TEST-USER] user is logged in to OncoCare application
And the browser size is set to: width=1920, height=1080
And test patients are copied from '\testdata\patients\prepared\macronav\' to '\tools\TestDataGeneration\basePatientData\'
And the test patients are generated by the '\tools\TestDataGeneration\prepareTestData.sh' tool today
And the generated test patients are uploaded to PDS


@SRS-124.01
@manual
@srs
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68525,SysRS-68530
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_SRS/Manual_-_Functional/Functional_Service/Macro_Navigator_Section
Scenario: User can navigate to the events which are out of the time-box on the macro-navigator
Given the "OncoTestPatient, MacroNavMonth" patient is selected
And I navigated to the "Timeline" view
And the timeline view setting was reset to default
And the time-box on the macro-navigator includes the last 6 months of the patient's timeline
When I scroll the timeline to the left side by using the horizontal scrollbar
Then the first 6 months of the patient's timeline are visible
And the 'Report 365 days ago' event is visible on the timeline
And the time-box on the macro-navigator is moved to the left side
And the 'Report 365 days ago' event is in the time-box on the macro-navigator
When I drag the time-box on the macro-navigator to the right side
Then the patient's last 6 months are visible on the timeline
And the 'Report 6 months ago' event is in the time-box on the macro-navigator
And the 'Report 6 months ago' event is visible on the timeline

@SRS-124.02
@sanity
@manual
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68525
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_Sanity-Exploratory/VPR_List_ME1_-_Manual/Functional_Service/Macro_Navigator_Section
Scenario: Macro-navigator time-box size is changing according to the timeline zoom level
Given the "OncoTestPatient, MacroNavYear" patient is selected
And the timeline view setting was reset to default
And I navigated to the "Timeline" view
And the time-box on the macro-navigator includes the last 6 months of the patient's timeline
When I click on the 'All time' button in the timeline toolbar
Then the whole patient timeline is visible on the timeline
And the time-box on the macro-navigator covers the whole patient timeline
When I zoom in the timeline to the max zoom level
And I scroll the timeline to the left side
Then the 'Report 10 years ago' event is in the time-box on the macro-navigator
And the 'Report 10 years ago' event is visible on the timeline
And the 'Report 5 years ago' event is NOT in the time-box on the macro-navigator
And the 'Report 5 years ago' event is NOT visible on the timeline
When I fully zoom out the timeline by using the zoom slider
Then the time-box on the macro-navigator covers the whole patient's timeline
And the 'Report 10 years ago' event is in the time-box on the macro-navigator
And the 'Report today' event is in the time-box on the macro-navigator
And the 'Report 10 years ago' event is visible on the timeline
And the 'Report today' event is visible on the timeline

@SRS-124.04
@manual
@srs
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68525
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_SRS/Manual_-_Functional/Functional_Service/Macro_Navigator_Section
Scenario: Navigate to a specific year on the macro-navigator
Given the "OncoTestPatient, MacroNavYear" patient is selected
And I navigated to the "Timeline" view
And the macro-navigator is displayed above the timeline
When I check the macro-navigator above the timeline
Then the date format on the timeline axis on the macro-navigator is 'YYYY'
And the axis visible on top of the Timeline and the Navigator
When I click on the 'All time' button in the timeline toolbar
Then the time-box on the macro-navigator covers the whole patient timeline
When I click on the 4th link from the left on the timeline axis on the macro-navigator (e.g. 2017)
Then the timeline is zoomed in to the selected year
And only the selected year is covered by the time-box on the macro-navigator
When I click on the 'All time' button in the timeline toolbar
And I change the 'Timeline direction' on the 'Settings' page to show the 'Newest event on left'
And I navigate back to the "Timeline" view
And I click on the 5th link from the left on the timeline axis on the macro-navigator
Then the timeline is zoomed in to the selected year
And only the selected year is covered by the time-box on the macro-navigator

@SRS-124.05
@manual
@srs
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68525
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_SRS/Manual_-_Functional/Functional_Service/Macro_Navigator_Section
Scenario: Navigate to a specific month on the macro-navigator
Given the "OncoTestPatient, MacroNavMonth" patient is selected
And I navigated to the "Timeline" view
And the macro-navigator is displayed above the timeline
When I check the macro-navigator above the timeline
Then the date format on the timeline axis on the macro-navigator is 'YYYY Mon' or 'Mon'
And the time-box on the macro-navigator covers the last 6 months of the patient
When I click on the 4th link from the left on the timeline axis on the macro-navigator (e.g. Feb)
Then the timeline is zoomed in to the selected month
And only the selected month is covered by the time-box on the macro-navigator

@SRS-124.06
@manual
@srs
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68525
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_SRS/Manual_-_Functional/Functional_Service/Macro_Navigator_Section
Scenario Outline: Navigate to a specific day on the macro-navigator
Given the "<patient_name>" patient is selected
And I navigated to the "Timeline" view
And the macro-navigator is displayed above the timeline
When I check the macro-navigator above the timeline
Then the date format on the timeline axis on the macro-navigator is 'YYYY Mon DD' or 'Mon DD'
When I click on the 4th link from the left on the timeline axis on the macro-navigator (e.g. Apr 22)
Then the timeline is zoomed in to the selected day
And only the selected day is covered by the time-box on the macro-navigator
Examples:
| patient_name                  |
| OncoTestPatient, MacroNavDay  |
| OncoTestPatient, MacroNavDay2 |

@SRS-124.07
@manual
@srs
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68525
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_SRS/Manual_-_Functional/Functional_Service/Macro_Navigator_Section
Scenario Outline: Navigate to the current day on the macro-navigator (newest event on the right)
Given the timeline direction is set to "Newest event on the right (default)"
And the "<patient_name>" patient is selected
And I navigated to the "Timeline" view
And the macro-navigator is displayed above the timeline
And the 'Now' link is on the right side of the macro-navigator
When I click on the 'Now' link on the macro-navigator
Then the timeline is fully zoomed in
And the time-box on the macro-navigator is moved to the right side
And timeline is scrolled to the right side
Examples:
| patient_name                   |
| OncoTestPatient, MacroNavDay   |
| OncoTestPatient, MacroNavMonth |

@SRS-124.08
@manual
@srs
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68525
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_SRS/Manual_-_Functional/Functional_Service/Macro_Navigator_Section
Scenario: Navigate to the current day on the macro-navigator (newest event on the left)
Given the timeline direction is set to "Newest event on the left"
And the "OncoTestPatient, MacroNavYear" patient is selected
And I navigated to the "Timeline" view
And the macro-navigator is displayed above the timeline
And the 'Now' link is on the left side of the macro-navigator
When I click on the 'Now' link on the macro-navigator
Then the timeline is fully zoomed in
And the time-box on the macro-navigator is moved to the left side
And timeline is scrolled to the left side
