Feature: [SysRS-68524] Macro navigator swimlanes and events

Narrative: The system Timeline view shall have a Macro navigator with swimlanes and events represented by dots.


Background:
Given the [DEFAULT-TEST-USER] user is logged in to OncoCare application
And the browser size is set to: width=1920, height=1080


@SRS-123.01
@sanity
@manual
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68530,SysRS-68524
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_Sanity-Exploratory/VPR_List_ME1_-_Manual/Functional_Service/Macro_Navigator_Section
Scenario: The whole patient timeline is displayed on the macro-navigator and the last 6 months are visible on the timeline by default
Given test patients are copied from '\testdata\patients\prepared\macronav\' to '\tools\TestDataGeneration\basePatientData\'
And the test patients are generated by the '\tools\TestDataGeneration\prepareTestData.sh' tool today
And the generated test patients are uploaded to PDS
And the "OncoTestPatient, MacroNavMonth" patient is selected
And the timeline view setting was reset to default
When I navigate to the "Timeline" view
Then the macro-navigator is displayed above the timeline
And the macro-navigator displays a year long patient timeline including 6 events
And the time-box on the macro-navigator includes the last 6 months of the patient's timeline
And the patient's last 6 months are visible on the timeline
And the 'Report 6 months ago' event is in the time-box on the macro-navigator
And the 'Report 6 month ago' event is visible on the timeline

@SRS-123.02
@edge
@sanity
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68524
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_Sanity-Exploratory/VPR_List_ME1_-_Automated/Functional_Service/Macro_Navigator_Section
Scenario: Selected event is highlighted on the macro navigator
Given the dates of the following patient's resources are prepared and uploaded to PDS: patients/prepared/macronav/OncoTestPatient_MacroNavMonth.json
And the page is reloaded
And the "OncoTestPatient, MacroNavMonth" patient is selected
And the user navigated to the "Timeline" view
And the patient timeline is displayed
And the macro-navigator is displayed
And the "Pathology and Labs" swimlane on macro-navigator contains the below event points:
| index | is_filtered | selected |
| 0     | false       | false    |
| 1     | false       | false    |
| 2     | false       | false    |
| 3     | false       | false    |
| 4     | false       | false    |
| 5     | false       | false    |
When the user hovers the following event point on the "Pathology and Labs" swimlane:
| event_type | name_on_label      |
| MARKER     | Report 68 days ago |
Then the "Pathology and Labs" swimlane on macro-navigator contains the below event points:
| index | is_filtered | selected |
| 0     | false       | false    |
| 1     | false       | false    |
| 2     | false       | false    |
| 3     | false       | false    |
| 4     | false       | false    |
| 5     | false       | false    |
When the user clicks on the following event point on the "Pathology and Labs" swimlane:
| event_type | name_on_label      |
| MARKER     | Report 68 days ago |
Then the sidebar is displayed
And the "Pathology and Labs" swimlane on macro-navigator contains the below event points:
| index | is_filtered | selected |
| 0     | false       | false    |
| 1     | false       | false    |
| 2     | false       | true     |
| 3     | false       | false    |
| 4     | false       | false    |
| 5     | false       | false    |
When the user clicks on the Close button on the sidebar
Then the sidebar is not displayed
And the "Pathology and Labs" swimlane on macro-navigator contains the below event points:
| index | is_filtered | selected |
| 0     | false       | false    |
| 1     | false       | false    |
| 2     | false       | false    |
| 3     | false       | false    |
| 4     | false       | false    |
| 5     | false       | false    |

@SRS-123.03
@manual
@srs
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68524
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_SRS/Manual_-_Functional/Functional_Service/Macro_Navigator_Section
Scenario: Chemo regimens are displayed on the macro-navigator
Given the "OncoTestPatient, Dolores" patient is selected
And I navigated to the "Timeline" view
And the macro-navigator is displayed above the timeline
When I fully zoom out the timeline
Then I see that the same chemo regimens are displayed on the timeline and on the macro-navigator
When I mark the below event as important on the "Treatment and Plan" swimlane:
| event_name                              | event_date   |
| cyclophosphamide (CYTOXAN) chemo tablet | Dec 09, 2009 |
And I filter for the important events in the timeline toolbar
Then I see that all events became transparent on the macro-navigator except the event which was marked as important
And I see that all chemo regimens are still displayed on the macro-navigator

@SRS-123.04
@sanity
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68524
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_Sanity-Exploratory/VPR_List_ME1_-_Automated/Functional_Service/Macro_Navigator_Section
Scenario: Selected event in an event cluster pill is highlighted on the macro navigator
Given the dates of the following patient's resources are prepared and uploaded to PDS: patients/prepared/macronav/OncoTestPatient_MacroNavDay.json
And the page is reloaded
And the "OncoTestPatient, MacroNavDay" patient is selected
And the user navigated to the "Timeline" view
And the patient timeline is displayed
And the macro-navigator is displayed
When the user hovers the following event point on the "Pathology and Labs" swimlane:
| event_type | text_on_event_point | name_on_label | date_on_timeline_axis       |
| CLUSTER    | 2                   | 2 events      | <5_DAYS_AGO> - <5_DAYS_AGO> |
Then the "Pathology and Labs" swimlane on macro-navigator contains the below event points:
| index | is_filtered | selected |
| 0     | false       | false    |
| 1     | false       | false    |
| 2     | false       | false    |
| 3     | false       | false    |
| 4     | false       | false    |
| 5     | false       | false    |
| 6     | false       | false    |
| 7     | false       | false    |
When the user clicks on the following event point on the "Pathology and Labs" swimlane:
| event_type | text_on_event_point | name_on_label | date_on_timeline_axis       |
| CLUSTER    | 2                   | 2 events      | <5_DAYS_AGO> - <5_DAYS_AGO> |
Then the cluster pill is opened
And the "Pathology and Labs" swimlane on macro-navigator contains the below event points:
| index | is_filtered | selected |
| 0     | false       | false    |
| 1     | false       | false    |
| 2     | false       | false    |
| 3     | false       | false    |
| 4     | false       | false    |
| 5     | false       | false    |
| 6     | false       | false    |
| 7     | false       | false    |
When the user selects the following event from the cluster pill:
| event_name            |
| Report 5 days ago - 2 |
Then the sidebar is displayed
And the "Pathology and Labs" swimlane on macro-navigator contains the below event points:
| index | is_filtered | selected |
| 0     | false       | false    |
| 1     | false       | false    |
| 2     | false       | false    |
| 3     | false       | true     |
| 4     | false       | false    |
| 5     | false       | false    |
| 6     | false       | false    |
| 7     | false       | false    |
When the user clicks on the Close button on the sidebar
Then the sidebar is not displayed
And the "Pathology and Labs" swimlane on macro-navigator contains the below event points:
| index | is_filtered | selected |
| 0     | false       | false    |
| 1     | false       | false    |
| 2     | false       | false    |
| 3     | false       | false    |
| 4     | false       | false    |
| 5     | false       | false    |
| 6     | false       | false    |
| 7     | false       | false    |

@SRS-123.05
@sanity
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68524
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_Sanity-Exploratory/VPR_List_ME1_-_Automated/Functional_Service/Macro_Navigator_Section
Scenario: Re-arrange swimlanes is applied on the macro-navigator
Given the dates of the following patient's resources are prepared and uploaded to PDS: patients/prepared/macronav/OncoTestPatient_MacroNavYear.json
And [API] the default swimlane order was set by the [DEFAULT-TEST-USER] user
And the page is reloaded
And the "OncoTestPatient, MacroNavYear" patient is selected
And the user navigated to the "Timeline" view
And the patient timeline is displayed
And the macro-navigator is displayed
And the swimlanes are available on the macro-navigator in the following order:
| swimlane_name      | is_filtered |
| Encounters         | false       |
| Imaging            | false       |
| Pathology and Labs | false       |
| Biomarkers         | false       |
| Treatment and Plan | false       |
| Uncategorized      | false       |
When the user navigates to the Settings page
And the user clicks on 'Edit' button at the following user setting:
| settings_title | setting_name   |
| Timeline       | Swimlane order |
And the user sets the following "Swimlane order" list in "Timeline" section:
| swimlane_name      |
| Treatment and Plan |
| Encounters         |
| Pathology and Labs |
| Biomarkers         |
| Uncategorized      |
| Imaging            |
And the user clicks on the "Save" button on the Settings page
And the user clicks on the "Back" button in the Settings toolbar header
Then the patient timeline is loaded
And the macro-navigator is displayed
And the swimlanes are available on the macro-navigator in the following order:
| swimlane_name      | is_filtered |
| Treatment and Plan | false       |
| Encounters         | false       |
| Pathology and Labs | false       |
| Biomarkers         | false       |
| Uncategorized      | false       |
| Imaging            | false       |
When the user navigates to the Settings page
And the user clicks on 'Edit' button at the following user setting:
| settings_title | setting_name   |
| Timeline       | Swimlane order |
And the user clicks on the "Reset to default" button on the Settings page
And the user clicks on the "Save" button on the Settings page
And the user clicks on the "Back" button in the Settings toolbar header
Then the patient timeline is loaded
And the macro-navigator is displayed
And the swimlanes are available on the macro-navigator in the following order:
| swimlane_name      | is_filtered |
| Encounters         | false       |
| Imaging            | false       |
| Pathology and Labs | false       |
| Biomarkers         | false       |
| Treatment and Plan | false       |
| Uncategorized      | false       |

@SRS-123.06
@manual
@srs
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68524
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_SRS/Manual_-_Functional/Functional_Service/Macro_Navigator_Section
Scenario: Timeline direction setting is applied on the macro-navigator
Given test patients are copied from '\testdata\patients\prepared\macronav\' to '\tools\TestDataGeneration\basePatientData\'
And the test patients are generated by the '\tools\TestDataGeneration\prepareTestData.sh' tool today
And the generated test patients are uploaded to PDS
And the "OncoTestPatient, MacroNavYear" patient is selected
And the timeline view setting was reset to default
And I navigated to the "Timeline" view
And the time-box on the macro-navigator includes the last 6 months of the patient's timeline
When I check the macro-navigator above the timeline
Then the 'Now' link is displayed on the right side of the macro-navigator
And the timeline axis values on the macro-navigator are ascending from left to the right
And the time-box is on the right side of the macro-navigator
When I change the 'Timeline direction' on the 'Settings' page to show the 'Newest event on left'
And I navigate back to the "Timeline" view
Then the 'Now' link is displayed on the left side of the macro-navigator
And the timeline axis values on the macro-navigator are descending from left to the right
And the time-box is on the left side of the macro-navigator
When I change the 'Timeline direction' on the 'Settings' page to show the 'Newest event on right (default)'
And I navigate back to the "Timeline" view
Then the 'Now' link is displayed on the right side of the macro-navigator
And the timeline axis values on the macro-navigator are ascending from left to the right
And the time-box is on the right side of the macro-navigator
