Feature: [SysRS-68526] Macro navigator show/hide

Narrative: The system shall be able to show/hide Macro navigator.


Background:
Given the [DEFAULT-TEST-USER] user is logged in to OncoCare application
And the browser size is set to: width=1920, height=1080

@sanity
@edge
@SRS-125.01
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68526
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_Sanity-Exploratory/VPR_List_ME1_-_Automated/Functional_Service/Macro_Navigator_Section
Scenario: Macro-navigator can be hidden by using the timeline toolbar
Given the dates of the following patient's resources are prepared and uploaded to PDS: patients/prepared/macronav/OncoTestPatient_MacroNavYear.json
And [API] the default swimlane order was set by the [DEFAULT-TEST-USER] user
And the page is reloaded
And the "OncoTestPatient, MacroNavYear" patient is selected
When the user navigates to the "Timeline" view
Then the patient timeline is displayed
And the macro-navigator is displayed
When the user selects the "Hide Navigator" checkbox on the timeline toolbar
Then the macro-navigator is not displayed
When the user unselects the "Hide Navigator" checkbox on the timeline toolbar
Then the macro-navigator is displayed

@SRS-125.02
@manual
@srs
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68526
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_SRS/Manual_-_Functional/Functional_Service/Macro_Navigator_Section
Scenario: Macro-navigator can be hidden by using the button on the macro-navigator area
Given test patients are copied from '\testdata\patients\prepared\macronav\' to '\tools\TestDataGeneration\basePatientData\'
And the test patients are generated by the '\tools\TestDataGeneration\prepareTestData.sh' tool today
And the generated test patients are uploaded to PDS
And the "OncoTestPatient, MacroNavYear" patient is selected
And I navigated to the "Timeline" view
And the macro-navigator is displayed above the timeline
And the 'Hide navigator' checkbox is unselected on the timeline toolbar
When I zoom in the timeline to max zoom level
And I navigate to the right side of the timeline
Then only the 'Report today' event is displayed in the time-box on the macro-navigator
When I click on the 'Hide navigator' button on the top left side of the macro-navigator
Then the macro-navigator is NOT displayed above the timeline
And the 'Hide navigator' checkbox is selected on the timeline toolbar
When I click on the 'All time' button in the timeline toolbar
And I unselect the 'Hide navigator' checkbox on the timeline toolbar
Then the macro-navigator is displayed above the timeline
And the time-box on the macro-navigator covers the whole patient timeline
