Feature: [SysRS-68567] Last 30 And Last 90 Days On Trends Cards

Narrative: The system users shall provide the user the ability to select to see last 30 days, last 90 days or all time data on the trend cards.


@SRS-139.01
@sanity
@manual
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68567
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_Sanity-Exploratory/VPR_List_ME1_-_Manual/Functional_Service/Trends_View
Scenario Outline: Trends dashboard can display the data points from the "Last 30 days"
Given the "OncoTestPatient, Trendenza" patient test data is generated by '\tools\TestDataGeneration\prepareTestData.sh' tool
And the replaced date parameters which were logged by the 'prepareTestData.sh' tool are noted
And the generated test data ('\tools\TestDataGeneration\generated\OncoTestPatient_Trendenza_generated.json') is uploaded to PDS
And I logged in to OncoCare application
And I selected the "OncoTestPatient, Trendenza" patient
When I navigate to the "Trends" dashboard
And I select the "<view_option>" option in the Trends toolbar
And I select the "Last 30 days" option in the Trends toolbar
Then I see only the following data points on the "Hemoglobin [Mass/volume] in Blood (g/dL)" trend graph:
| data_value_on_point_label | date_on_point_label |
| 26.123                    | <30_DAYS_AGO>       |
| 27.576                    | <29_DAYS_AGO>       |
| 25.288                    | <16_DAYS_AGO>       |
| 31.411                    | <TODAY>             |
And the data points are connected by straight lines
And the horizontal axis is in the following range:
| start_date               | end_date           |
| <30_DAYS_AGO>            | <TODAY>            |
And the vertical axis is in the following range:
| start                    | end                |
| 0                        | 40                 |
When I select the "All time" option in the Trends toolbar
Then I see the following data points on the "Hemoglobin [Mass/volume] in Blood (g/dL)" trend graph:
| data_value_on_point_label | date_on_point_label |
| 15.445                    | <98_DAYS_AGO>       |
| 11.987                    | <90_DAYS_AGO>       |
| 21.541                    | <89_DAYS_AGO>       |
| 23.334                    | <73_DAYS_AGO>       |
| 26.123                    | <30_DAYS_AGO>       |
| 27.576                    | <29_DAYS_AGO>       |
| 25.288                    | <16_DAYS_AGO>       |
| 31.411                    | <TODAY>             |
Examples:
| view_option |
| Grid view   |
| List view   |

@SRS-139.02
@manual
@srs
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68567
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_SRS/Manual_-_Functional/Functional_Service/Trends_View
Scenario Outline: Trends dashboard can display the data points from the "Last 90 days"
Given the "OncoTestPatient, Trendenza" patient test data is generated by '\tools\TestDataGeneration\prepareTestData.sh' tool
And the replaced date parameters which were logged by the 'prepareTestData.sh' tool are noted
And the generated test data ('\tools\TestDataGeneration\generated\OncoTestPatient_Trendenza_generated.json') is uploaded to PDS
And I logged in to OncoCare application
And I selected the "OncoTestPatient, Trendenza" patient
When I navigate to the "Trends" dashboard
And I select the "<view_option>" option in the Trends toolbar
And I select the "Last 90 days" option in the Trends toolbar
Then I see only the following data points on the "Hemoglobin [Mass/volume] in Blood (g/dL)" trend graph:
| data_value_on_point_label | date_on_point_label |
| 11.987                    | <90_DAYS_AGO>       |
| 21.541                    | <89_DAYS_AGO>       |
| 23.334                    | <73_DAYS_AGO>       |
| 26.123                    | <30_DAYS_AGO>       |
| 27.576                    | <29_DAYS_AGO>       |
| 25.288                    | <16_DAYS_AGO>       |
| 31.411                    | <TODAY>             |
And the data points are connected by straight lines
And the horizontal axis is in the following range:
| start_date               | end_date           |
| <90_DAYS_AGO>            | <TODAY>            |
And the vertical axis is in the following range:
| start                    | end                |
| 0                        | 40                 |
When I select the "All time" option in the Trends toolbar
Then I see the following data points on the "Hemoglobin [Mass/volume] in Blood (g/dL)" trend graph:
| data_value_on_point_label | date_on_point_label |
| 15.445                    | <98_DAYS_AGO>       |
| 11.987                    | <90_DAYS_AGO>       |
| 21.541                    | <89_DAYS_AGO>       |
| 23.334                    | <73_DAYS_AGO>       |
| 26.123                    | <30_DAYS_AGO>       |
| 27.576                    | <29_DAYS_AGO>       |
| 25.288                    | <16_DAYS_AGO>       |
| 31.411                    | <TODAY>             |
Examples:
| view_option |
| Grid view   |
| List view   |
