Feature: [SysRS-68570] Save Trends State Per Patient

Narrative: The system shall save the following Trend dashboard view settings on patient level:
             - Time range
             - Layout
             - Reference range visibility.


Background:
Given the "OncoTestPatient, Trendenza" patient test data is generated by '\tools\TestDataGeneration\prepareTestData.sh' tool
And the generated test data ('\tools\TestDataGeneration\generated\OncoTestPatient_Trendenza_generated.json') is uploaded to PDS


@SRS-209.01
@manual
@srs
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68570,SysRS-103345
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_SRS/Manual_-_Functional/Functional_Service/Trends_View
Scenario: Trends view state is kept when user changes tabs
Given I logged in to OncoCare application as [DEFAULT-TEST-USER] user
And I selected the "OncoTestPatient, Trendenza" patient
And I navigated to the "Trends" dashboard
When I select the "List view" option in the Trends toolbar
And I select the "Reference range" option in the Trends toolbar
And I select the "Last 90 days" option in the Trends toolbar
And I navigate to the Summary view
And I navigate back to the "Trends" dashboard
Then the "List view" option is selected in the Trends toolbar
And the charts are displayed in list view
And the "Reference range" option is selected in the Trends toolbar
And reference range info is displayed on the charts
And the "Last 90 days" option is selected in the Trends toolbar
And the horizontal axis is in the following range on all charts:
| start_date    | end_date |
| <90_DAYS_AGO> | <TODAY>  |

@SRS-209.02
@manual
@srs
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68570,SysRS-103345
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_SRS/Manual_-_Functional/Functional_Service/Trends_View
Scenario: Trends view state is saved per patient
Given I logged in to OncoCare application as [DEFAULT-TEST-USER] user
And I selected the "OncoTestPatient, Trendenza" patient
And I navigated to the "Trends" dashboard
When I select the "List view" option in the Trends toolbar
And I unselect the "Reference range" option in the Trends toolbar (if it is checked in)
And I set the following custom date range:
| start_date    | end_date      |
| <73_DAYS_AGO> | <16_DAYS_AGO> |
And I select the "OncoTestPatient, Freya" patient
And I navigate to the "Trends" dashboard
And I select the "Grid view" option in the Trends toolbar
And I select the "Reference range" option in the Trends toolbar
And I select the "Last 30 days" option in the Trends toolbar
And I select the "OncoTestPatient, Trendenza" patient
And I navigate to the "Trends" dashboard
Then the "List view" option is selected in the Trends toolbar
And the charts are displayed in list view
And the "Reference range" option is unselected in the Trends toolbar
And reference range info is not displayed on the charts
And the following custom date range is set in the Trends toolbar:
| start_date    | end_date      |
| <73_DAYS_AGO> | <16_DAYS_AGO> |
And the horizontal axis is in the following range on all charts:
| start_date    | end_date      |
| <73_DAYS_AGO> | <16_DAYS_AGO> |
When I select the "OncoTestPatient, Freya" patient
And I navigate to the "Trends" dashboard
Then the "Grid view" option is selected in the Trends toolbar
And the charts are displayed in grid view
And the "Reference range" option is selected in the Trends toolbar
And reference range info is displayed on the charts
And the "Last 30 days" option is selected in the Trends toolbar
And the horizontal axis is in the following range on all charts:
| start_date    | end_date |
| <30_DAYS_AGO> | <TODAY>  |

@SRS-209.03
@manual
@srs
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68570,SysRS-103345
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_SRS/Manual_-_Functional/Functional_Service/Trends_View
Scenario: Trends view state is saved per user per patient
Given I logged in to OncoCare application as [DEFAULT-TEST-USER] user
And I selected the "OncoTestPatient, Trendenza" patient
And I navigated to the "Trends" dashboard
When I select the "List view" option in the Trends toolbar
And I select the "Reference range" option in the Trends toolbar
And I set the following custom date range:
| start_date    | end_date      |
| <98_DAYS_AGO> | <11_DAYS_AGO> |
And I log out from the application
And I login to OncoCare application as [TEST-USER-2] user
And I select the "OncoTestPatient, Trendenza" patient
And I select the "Grid view" option in the Trends toolbar
And I select the "Reference range" option in the Trends toolbar
And I select the "Last 90 days" option in the Trends toolbar
And I log out from the application
And I login to OncoCare application as [DEFAULT-TEST-USER] user
And I select the "OncoTestPatient, Trendenza" patient
And I navigate to the "Trends" dashboard
Then the "List view" option is selected in the Trends toolbar
And the charts are displayed in list view
And the "Reference range" option is selected in the Trends toolbar
And reference range info is displayed on the charts
And the following custom date range is set in the Trends toolbar:
| start_date    | end_date      |
| <98_DAYS_AGO> | <11_DAYS_AGO> |
And the horizontal axis is in the following range on all charts:
| start_date    | end_date      |
| <98_DAYS_AGO> | <11_DAYS_AGO> |
When I log out from the application
And I login to OncoCare application as [TEST-USER-2] user
And I select the "OncoTestPatient, Trendenza" patient
And I navigate to the "Trends" dashboard
Then the "Grid view" option is selected in the Trends toolbar
And the charts are displayed in grid view
And the "Reference range" option is selected in the Trends toolbar
And reference range info is displayed on the charts
And the "Last 90 days" option is selected in the Trends toolbar
And the horizontal axis is in the following range on all charts:
| start_date    | end_date |
| <90_DAYS_AGO> | <TODAY>  |

@SRS-209.04
@manual
@srs
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68570,SysRS-103345
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_SRS/Manual_-_Functional/Functional_Service/Trends_View
Scenario: Trends view state is kept when the page is reloaded
Given I logged in to OncoCare application as [DEFAULT-TEST-USER] user
And I selected the "OncoTestPatient, Trendenza" patient
And I navigated to the "Trends" dashboard
When I select the "List view" option in the Trends toolbar
And I select the "Reference range" option in the Trends toolbar
And I set the following custom date range:
| start_date    | end_date      |
| <98_DAYS_AGO> | <30_DAYS_AGO> |
And I refresh the page in the browser's toolbar
Then the page is reloaded
And the "List view" option is selected in the Trends toolbar
And the charts are displayed in list view
And the "Reference range" option is selected in the Trends toolbar
And reference range info is displayed on the charts
And the following custom date range is set in the Trends toolbar:
| start_date    | end_date      |
| <98_DAYS_AGO> | <30_DAYS_AGO> |
And the horizontal axis is in the following range on all charts:
| start_date    | end_date      |
| <98_DAYS_AGO> | <30_DAYS_AGO> |

@SRS-209.05
@manual
@srs
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68570,SysRS-68399,SysRS-103345
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_SRS/Manual_-_Functional/Functional_Service/Trends_View
Scenario: Trends view state is kept when the patient data is refreshed
Given I logged in to OncoCare application as [DEFAULT-TEST-USER] user
And I selected the "OncoTestPatient, Trendenza" patient
And I navigated to the "Trends" dashboard
When I select the "List view" option in the Trends toolbar
And I select the "Reference range" option in the Trends toolbar
And I set the following custom date range:
| start_date    | end_date      |
| <89_DAYS_AGO> | <30_DAYS_AGO> |
And [API] I upload the "OncoTestPatient, Trendenza" patient to PDS again ('\tools\TestDataGeneration\generated\OncoTestPatient_Trendenza_generated.json')
And I wait for following patient sync banner:
| banner_message_regex           | button_in_banner |
| Patient data update available. | Refresh          |
And I click on the "Refresh" button in the patient sync banner
Then the page is reloaded
And the "List view" option is selected in the Trends toolbar
And the charts are displayed in list view
And the "Reference range" option is selected in the Trends toolbar
And reference range info is displayed on the charts
And the following custom date range is set in the Trends toolbar:
| start_date    | end_date      |
| <89_DAYS_AGO> | <30_DAYS_AGO> |
And the horizontal axis is in the following range on all charts:
| start_date    | end_date      |
| <89_DAYS_AGO> | <30_DAYS_AGO> |
When I select the "OncoTestPatient, Juno" patient
And I select the "OncoTestPatient, Trendenza" patient again
And I navigate to the "Trends" dashboard
And [API] I upload the "OncoTestPatient, Trendenza" patient to PDS again ('\tools\TestDataGeneration\generated\OncoTestPatient_Trendenza_generated.json')
And I wait for following patient sync banner:
| banner_message_regex           | button_in_banner |
| Patient data update available. | Refresh          |
And I click on the "Refresh" button in the patient sync banner
Then the page is reloaded
And the "List view" option is selected in the Trends toolbar
And the charts are displayed in list view
And the "Reference range" option is selected in the Trends toolbar
And reference range info is displayed on the charts
And the following custom date range is set in the Trends toolbar:
| start_date    | end_date      |
| <89_DAYS_AGO> | <30_DAYS_AGO> |
And the horizontal axis is in the following range on all charts:
| start_date    | end_date      |
| <89_DAYS_AGO> | <30_DAYS_AGO> |

@SRS-209.06
@manual
@srs
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68570,SysRS-68573
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_SRS/Manual_-_Functional/Functional_Service/Trends_View
Scenario: Error message is not displayed when saving the trends view state was unsuccessful
Given I logged in to OncoCare application as [DEFAULT-TEST-USER] user
And I selected the "OncoTestPatient, Trendenza" patient
And I navigated to the "Trends" dashboard
And I select the "Last 90 days" option in the Trends toolbar
And [DEVTOOLS] - the following text patterns were added to "Network request blocking" tool:
| text pattern  |
| settings      |
When [DEVTOOLS] - the user checks "Enable network request blocking" checkbox
And I select the "Last 30 days" option in the Trends toolbar
Then error message is not displayed on the screen
And the "Last 30 days" option is selected in the Trends toolbar
And the horizontal axis is in the following range on all charts:
| start_date    | end_date |
| <30_DAYS_AGO> | <TODAY>  |
When [DEVTOOLS] - the user unchecks "Enable network request blocking" checkbox
And I refresh the page in the browser's toolbar
Then the page is reloaded
And the "Last 90 days" option is selected in the Trends toolbar
And the horizontal axis is in the following range on all charts:
| start_date    | end_date |
| <90_DAYS_AGO> | <TODAY>  |
