Feature: [SysRS-68564] Sync Vertical Markers On All Charts

Narrative: The system shall keep in sync the vertical markers on all the chart on the Trend dashboard.


@SRS-109.01
@manual
@srs
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68564
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_SRS/Manual_-_Functional/Functional_Service/Trends_View
Scenario: Vertical line is displayed on all trend graphs when mouse is moved over a data point - All time range
Given the "OncoTestPatient, Trendenza" patient test data is generated by '\tools\TestDataGeneration\prepareTestData.sh' tool
And the replaced date parameters which were logged by the 'prepareTestData.sh' tool are noted
And the generated test data ('\tools\TestDataGeneration\generated\OncoTestPatient_Trendenza_generated.json') is uploaded to PDS
And I logged in to OncoCare application
And I selected the "OncoTestPatient, Trendenza" patient
When I navigate to the "Trends" dashboard
Then I see the following data points on the "Hemoglobin [Mass/volume] in Blood (g/dL)" trend graph:
| data_value_on_point_label | date_on_point_label |
| 15.445                    | <98_DAYS_AGO>       |
| 11.987                    | <90_DAYS_AGO>       |
| 21.541                    | <89_DAYS_AGO>       |
| 23.334                    | <73_DAYS_AGO>       |
| 26.123                    | <30_DAYS_AGO>       |
| 27.576                    | <29_DAYS_AGO>       |
| 25.288                    | <16_DAYS_AGO>       |
| 31.411                    | <TODAY>             |
And I see the following data points on the "Body Weight (kg)" trend graph:
| data_value_on_point_label | date_on_point_label |
| 4.1                       | <98_DAYS_AGO>       |
| 4.9                       | <52_DAYS_AGO>       |
| 6.1                       | <16_DAYS_AGO>       |
| 4.9                       | <11_DAYS_AGO>       |
When I move the mouse over the data point on the "Hemoglobin [Mass/volume] in Blood (g/dL)" trend graph at date: <29_DAYS_AGO>
Then a purple vertical line is displayed at <29_DAYS_AGO> on the following graphs:
| trend_graph_title                                           |
| Cancer Ag 125 [Units/volume] in Serum or Plasma (kU/l)      |
| Body Weight (kg)                                            |
| Creatinine (mg/dL)                                          |
| Leukocytes [#/volume] in Blood by Automated count (10*3/uL) |
| Eosinophils [#/volume] in Blood by Automated count (10*3/uL)|
| Hemoglobin [Mass/volume] in Blood (g/dL)                    |
| Platelets [#/volume] in Blood by Automated count (10*3/uL)  |
| Bilirubin.total [Mass/volume] in Serum or Plasma (mg/dL)    |

@SRS-109.02
@manual
@srs
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68564
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_SRS/Manual_-_Functional/Functional_Service/Trends_View
Scenario: Vertical line is displayed on all trend graphs when mouse is moved over a data point - Last 30 days
Given the "OncoTestPatient, Trendenza" patient test data is generated by '\tools\TestDataGeneration\prepareTestData.sh' tool
And the replaced date parameters which were logged by the 'prepareTestData.sh' tool are noted
And the generated test data ('\tools\TestDataGeneration\generated\OncoTestPatient_Trendenza_generated.json') is uploaded to PDS
And I logged in to OncoCare application
And I selected the "OncoTestPatient, Trendenza" patient
When I navigate to the "Trends" dashboard
And I select the "Last 30 days" option in the Trends toolbar
Then I see the following data points on the "Hemoglobin [Mass/volume] in Blood (g/dL)" trend graph:
| data_value_on_point_label | date_on_point_label |
| 26.123                    | <30_DAYS_AGO>       |
| 27.576                    | <29_DAYS_AGO>       |
| 25.288                    | <16_DAYS_AGO>       |
| 31.411                    | <TODAY>             |
And I see the following data points on the "Body Weight (kg)" trend graph:
| data_value_on_point_label | date_on_point_label |
| 6.1                       | <16_DAYS_AGO>       |
| 4.9                       | <11_DAYS_AGO>       |
When I move the mouse over the data point on the "Hemoglobin [Mass/volume] in Blood (g/dL)" trend graph at date: <16_DAYS_AGO>
Then a purple vertical line is displayed at <16_DAYS_AGO> on the following graphs:
| trend_graph_title                                           |
| Cancer Ag 125 [Units/volume] in Serum or Plasma (kU/l)      |
| Body Weight (kg)                                            |
| Creatinine (mg/dL)                                          |
| Leukocytes [#/volume] in Blood by Automated count (10*3/uL) |
| Eosinophils [#/volume] in Blood by Automated count (10*3/uL)|
| Hemoglobin [Mass/volume] in Blood (g/dL)                    |
| Platelets [#/volume] in Blood by Automated count (10*3/uL)  |
| Bilirubin.total [Mass/volume] in Serum or Plasma (mg/dL)    |

@SRS-109.03
@manual
@srs
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68564
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_SRS/Manual_-_Functional/Functional_Service/Trends_View
Scenario: Vertical line is displayed on all trend graphs when mouse is moved over a data point - Last 90 days in List view
Given the "OncoTestPatient, Trendenza" patient test data is generated by '\tools\TestDataGeneration\prepareTestData.sh' tool
And the replaced date parameters which were logged by the 'prepareTestData.sh' tool are noted
And the generated test data ('\tools\TestDataGeneration\generated\OncoTestPatient_Trendenza_generated.json') is uploaded to PDS
And I logged in to OncoCare application
And I selected the "OncoTestPatient, Trendenza" patient
When I navigate to the "Trends" dashboard
And I select the "List View" option in the Trends toolbar
And I select the "Last 90 days" option in the Trends toolbar
Then I see the following data points on the "Hemoglobin [Mass/volume] in Blood (g/dL)" trend graph:
| data_value_on_point_label | date_on_point_label |
| 11.987                    | <90_DAYS_AGO>       |
| 21.541                    | <89_DAYS_AGO>       |
| 23.334                    | <73_DAYS_AGO>       |
| 26.123                    | <30_DAYS_AGO>       |
| 27.576                    | <29_DAYS_AGO>       |
| 25.288                    | <16_DAYS_AGO>       |
| 31.411                    | <TODAY>             |
And I see the following data points on the "Body Weight (kg)" trend graph:
| data_value_on_point_label | date_on_point_label |
| 4.9                       | <52_DAYS_AGO>       |
| 6.1                       | <16_DAYS_AGO>       |
| 4.9                       | <11_DAYS_AGO>       |
When I move the mouse over the data point on the "Hemoglobin [Mass/volume] in Blood (g/dL)" trend graph at date: <73_DAYS_AGO>
Then a purple vertical line is displayed at <73_DAYS_AGO> on the following graphs:
| trend_graph_title                                           |
| Cancer Ag 125 [Units/volume] in Serum or Plasma (kU/l)      |
| Body Weight (kg)                                            |
| Creatinine (mg/dL)                                          |
| Leukocytes [#/volume] in Blood by Automated count (10*3/uL) |
| Eosinophils [#/volume] in Blood by Automated count (10*3/uL)|
| Hemoglobin [Mass/volume] in Blood (g/dL)                    |
| Platelets [#/volume] in Blood by Automated count (10*3/uL)  |
| Bilirubin.total [Mass/volume] in Serum or Plasma (mg/dL)    |
