Feature: [SysRS-68562] Visual Trends

Narrative: The system users shall be able to see visual Trend's of the patient’s weight, tumor marker (CA125, PSA), hemoglobin, platelets, creatinine and total bilirubin parameters on the trend dashboard in case these parameters have data for the patient.


@SRS-67.01
@manual
@srs
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68562
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_SRS/Manual_-_Functional/Functional_Service/Trends_View
Scenario: Trends of the patient's weight, tumor marker, WBC, hemoglobin, platelets, creatinine and total bilirubin parameters are displayed on Trends dashboard
Given the "OncoTestPatient, Trendenza" patient test data is generated by '\tools\TestDataGeneration\prepareTestData.sh' tool
And the replaced date parameters which were logged by the 'prepareTestData.sh' tool are noted
And the generated test data ('\tools\TestDataGeneration\generated\OncoTestPatient_Trendenza_generated.json') is uploaded to PDS
And I logged in to OncoCare application
And I selected the "OncoTestPatient, Trendenza" patient
When I navigate to the "Trends" view
Then I see the following trend graphs order:
| trend_graph_title                                           |
| Body Weight (kg)                                            |
| Cancer Ag 125 [Units/volume] in Serum or Plasma (kU/l)      |
| Leukocytes [#/volume] in Blood by Automated count (10*3/uL) |
| Eosinophils [#/volume] in Blood by Automated count (10*3/uL)|
| Hemoglobin [Mass/volume] in Blood (g/dL)                    |
| Platelets [#/volume] in Blood by Automated count (10*3/uL)  |
| Creatinine (mg/dL)                                          |
| Bilirubin.total [Mass/volume] in Serum or Plasma (mg/dL)    |
And there more trend tiles than screen real estate, the page becomes scrollable
And I do NOT see the following trend graph:
| trend_graph_title                                           |
| Body Height (cm)                                            |

@SRS-67.02
@srs
@manual
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68562
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_SRS/Manual_-_Functional/Functional_Service/Trends_View
Scenario: Trend graphs on Trends dashboard when the patient have no data for all possible trends
Given I logged in to OncoCare application
And I selected the "OncoTestPatient, SANDY A" patient
When I navigate to the "Trends" view
Then I see the following trend graphs:
| trend_graph_title    |
| Weight Measured (lb) |
| Weight Measured (kg) |
And I do NOT see information about any other trend data on Trends view

@SRS-67.03
@manual
@srs
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68562
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_SRS/Manual_-_Functional/Functional_Service/Trends_View
Scenario: Information message is displayed to the user when there is no data to show in Trends dashboard
Given I logged in to OncoCare application
And I selected the "OncoTestPatient, Empty" patient
When I navigate to the "Trends" view
Then the following information message is displayed:
| info_title      | info_message                                |
| No data to show | This patient has no data to show as trends. |

@SRS-67.04
@manual
@srs
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68562
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_SRS/Manual_-_Functional/Functional_Service/Trends_View
Scenario: Value and date information of trend graph data points are displayed on Trends dashboard
Given the "OncoTestPatient, Trendenza" patient test data is generated by '\tools\TestDataGeneration\prepareTestData.sh' tool
And the replaced date parameters which were logged by the 'prepareTestData.sh' tool are noted
And the generated test data ('\tools\TestDataGeneration\generated\OncoTestPatient_Trendenza_generated.json') is uploaded to PDS
And I logged in to OncoCare application
And I selected the "OncoTestPatient, Trendenza" patient
When I navigate to the "Trends" view
Then I see the "Body Weight (kg)" trend graph
When I hover the mouse over the data points on "Body Weight (kg)" trend graph
Then I see the value and date information of the following data points:
| data_value_on_point_label | date_on_point_label |
| 4.1                       | <98_DAYS_AGO>       |
| 4.9                       | <52_DAYS_AGO>       |
| 6.1                       | <16_DAYS_AGO>       |
| 4.9                       | <11_DAYS_AGO>       |
And the data points are connected by straight lines
And the horizontal axis is in the following range:
| start_date               | end_date           |
| Feb 17, 2023             | <TODAY>            |
And the vertical axis is in the following range:
| start                    | end                |
| 0                        | 8                  |
