Feature: [SysRS-68563] Vertical Markers On Trend Dashboards

Narrative: The system shall display vertical markers on the trend dashboards.


@SRS-108.01
@manual
@srs
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68563
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_SRS/Manual_-_Functional/Functional_Service/Trends_View
Scenario: Vertical line is displayed on the trend graph if the mouse is moved over a data point
Given the "OncoTestPatient, Trendenza" patient test data is generated by '\tools\TestDataGeneration\prepareTestData.sh' tool
And the replaced date parameters which were logged by the 'prepareTestData.sh' tool are noted
And the generated test data ('\tools\TestDataGeneration\generated\OncoTestPatient_Trendenza_generated.json') is uploaded to PDS
And I logged in to OncoCare application
And I selected the "OncoTestPatient, Trendenza" patient
And I navigated to the "Trends" dashboard
And I saw the following data points on the "Body Weight (kg)" trend graph:
| data_value_on_point_label | date_on_point_label |
| 4.1                       | <98_DAYS_AGO>       |
| 4.9                       | <52_DAYS_AGO>       |
| 6.1                       | <16_DAYS_AGO>       |
| 4.9                       | <11_DAYS_AGO>       |
When I move the mouse over the following data point on the "Body Weight (kg)" trend graph:
| data_value_on_point_label | date_on_point_label |
| 6.1                       | <16_DAYS_AGO>       |
Then a vertical line is displayed on the trend graph along with the hovered data point
When I move the mouse away from the hovered data point
Then the vertical line disappears
