Feature: [SysRS-68566] Trends cards view

Narrative: The system users shall be able to see the trend cards on the trend dashboard in grid or in list view.


@SRS-138.01
@SPR-4298
@manual
@srs
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68566
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_SRS/Manual_-_Functional/Functional_Service/Trends_View
Scenario: Trends dashboard can display the data points in a Grid View
Given the "OncoTestPatient, Trendenza" patient test data is generated by '\tools\TestDataGeneration\prepareTestData.sh' tool
And the generated test data ('\tools\TestDataGeneration\generated\OncoTestPatient_Trendenza_generated.json') is uploaded to PDS
And I logged in to OncoCare application
And I selected the "OncoTestPatient, Trendenza" patient
And I navigated to the "Trends" dashboard
When I select the "Grid View" option in the Trends toolbar
Then I see all the trend graph in Grid View

@SRS-138.02
@manual
@srs
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68566
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_SRS/Manual_-_Functional/Functional_Service/Trends_View
Scenario: Trends dashboard can display the data points in a List View
Given the "OncoTestPatient, Trendenza" patient test data is generated by '\tools\TestDataGeneration\prepareTestData.sh' tool
And the generated test data ('\tools\TestDataGeneration\generated\OncoTestPatient_Trendenza_generated.json') is uploaded to PDS
And I logged in to OncoCare application
And I selected the "OncoTestPatient, Trendenza" patient
And I navigated to the "Trends" dashboard
And the view is set to Grid View
When I select the "List View" option in the Trends toolbar
Then I see all the trend graph in List View
