Feature: [SysRS-68574] Reset Trends State Per Patient

Narrative: The system users shall be able to reset the trend dashboard settings to the default Trend dashboard view.


@SRS-213.01
@sanity
@manual
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68574
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_Sanity-Exploratory/VPR_List_ME1_-_Manual/Functional_Service/Trends_View
Scenario Outline: Default settings is applied when resetting the Trend settings - All time, Grid layout, Reference range is not selected
Given the "OncoTestPatient, Trendenza" patient test data is generated by '\tools\TestDataGeneration\prepareTestData.sh' tool
And the generated test data ('\tools\TestDataGeneration\generated\OncoTestPatient_Trendenza_generated.json') is uploaded to PDS
And I logged in to OncoCare application
And I selected the "OncoTestPatient, Trendenza" patient
When I navigate to the "Trends" dashboard
And I select the "<card_layout> in the Trends toolbar
And I select the "<date_range>" option in the Trends toolbar
And I <reference_range_state> the "Reference range" option in the More menu
Then the horizontal axis of the charts is in the following range:
| range        |
| <view_range> |
When I click "Reset to default view" in More menu on the Trends toolbar
Then the "All time" option is selected in the Trends toolbar
And the "Reference range" option is unselected in the More menu
And the "Grid view" option is selected in the Trends toolbar
And the horizontal axis is in the following range on all charts:
| start_date   | end_date |
| Feb 17, 2023 | <TODAY>  |
When I reload the page
Then the "All time" option is selected in the Trends toolbar
And the "Reference range" option is unselected in the More menu
And the "Grid view" option is selected in the Trends toolbar
And the horizontal axis is in the following range on all charts:
| start_date   | end_date |
| Feb 17, 2023 | <TODAY>  |
When I navigate to "Timeline" view
And I navigate to "Trends" view
Then the "All time" option is selected in the Trends toolbar
And the "Reference range" option is unselected in the More menu
And the "Grid view" option is selected in the Trends toolbar
And the horizontal axis is in the following range on all charts:
| start_date   | end_date |
| Feb 17, 2023 | <TODAY>  |
Examples:
| date_range          | card_layout | reference_range_state | view_range            |
| Last 30 days        | list view   | select                | <30_DAYS_AGO - TODAY> |
| Last 30 days        | grid view   | select                | <30_DAYS_AGO - TODAY> |
| Last 90 days        | list view   | select                | <90_DAYS_AGO - TODAY> |
| Last 90 days        | list view   | unselect              | <90_DAYS_AGO - TODAY> |
| 20 days ago - TODAY | list view   | select                | <20_DAYS_AGO - TODAY> |
| 20 days ago - TODAY | grid view   | unselect              | <20_DAYS_AGO - TODAY> |