@safety
Feature: [SysRS-68590] CLP Visualization

Narrative: The system shall have visual cue for data generated by AI Service / CLP.

@SRS-49.01
@sanity
@edge
@ai_sanity
@CLP
@Platform:WEB
@Category:Positive
@Traceability:SysRS-68590,SysRS-68596
@Path:CareIntellect_for_Oncology_1.0.0_VPR_for_System_Sanity-Exploratory/VPR_List_ME1_-_Automated/Functional_Service/Product_Messaging_Alarms_Warnings_And_Notifications
Scenario: Notification about AI-curated data is displayed on Summary view
Given [API] the CLP visualization is switched ON for [DEFAULT-TEST-USER] user
And the [DEFAULT-TEST-USER] user is logged in to OncoCare application
When the user selects the "OncoTestPatient, Juno" patient
Then the patient summary view is loaded
And the AI info on the Summary View contains the following text: "The data highlighted in blue or marked on this page is a summary produced by generative artificial intelligence and is intended to supplement the existing patient data, may be incomplete or incorrect, and is not intended to replace the provider's judgment or responsibility to review the source original clinical information."
